services:
  web:
    build:
      target: web
    ports:
    - "8000:8000"
    environment:
      CONNECTION_STRING: "postgresql+psycopg2://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@${DATABASE_HOSTNAME}/${DATABASE_NAME}"
      MASTER_API_TOKEN: $(MASTER_API_TOKEN)
  bot:
    build:
      target: bot
    environment:
      ADMIN_NAME: ${ADMIN_NAME}
      ADMIN_DISCORD_NAME: ${ADMIN_DISCORD_NAME}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DISCORD_GUILD_ID: ${DISCORD_GUILD_ID}
      CONNECTION_STRING: "postgresql+psycopg2://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@${DATABASE_HOSTNAME}/${DATABASE_NAME}"
  database:
    hostname: "${DATABASE_HOSTNAME}"
    image: "postgres:latest"
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}