import os

SERVER_NAME = "adibob"
SESSION_START_WEEKDAY = 4 # 0=Mon, 1=Tues ... 6=Sun
SESSION_START_TIME = 18
SESSION_END_WEEKDAY = 5 # Saturday
SESSION_END_TIME = 3

CONNECTION_STRING = os.environ.get("CONNECTION_STRING")
DISCORD_TOKEN = os.environ.get('DISCORD_TOKEN')
DISCORD_GUILD_ID = os.environ.get('DISCORD_GUILD_ID')